### ISSUE TITLE
Raises TypeError on files using relative import

### ISSUE THREAD

**Issue by perey** [ghewgill/pyqver#7]
At least, I'm pretty sure that relative imports are the only thing in common, across all modules producing the error below.

```
Traceback (most recent call last):
  File "<redacted>/pyqver3.py", line 267, in <module>
    ver = get_versions(source, fn)
  File "<redacted>/pyqver3.py", line 193, in get_versions
    checker.visit(tree)
  File "/usr/lib/python3.2/ast.py", line 248, in visit
    return visitor(node)
  File "/usr/lib/python3.2/ast.py", line 256, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.2/ast.py", line 248, in visit
    return visitor(node)
  File "<redacted>/pyqver3.py", line 174, in visit_ImportFrom
    name = node.module + "." + n.name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by benjaoming** [comment]
Getting this, too...
